---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# catterpoc

Test package (proof of concept) for behavior of import package for S3 methods.
Installation not recommended except to test that behavior.

## Examples

Import from package

```{r}

# catterpoc should not be loaded at start
testthat::expect_error(catter_a("hello"), "could not find function")

# catter_a
import::from(catterpoc, catter_a)
x <- catter_a("hello") 
x # print.catter_a not picked up

# catter_b
import::from(catterpoc, catter_b)
x <- catter_b("hello") 
x # print.catter_b NOT picked up either, even if .S3method was called

rm("catter_a", "catter_b", pos="imports")

```


Import from script/module

```{r}

# catterpoc should not be loaded at start
testthat::expect_error(catter_a("hello"), "could not find function")

# catter_a (using import)
import::from("R/catter.R", "catter_a",  .character_only=TRUE)
x <- catter_a("hello") 
x # print.catter_a not picked up

# catter_b (using import)
import::from("R/catter.R", "catter_b",  .character_only=TRUE)
x <- catter_b("hello") 
x # Here, it is picked up correctly (because .S3method was called)

rm("catter_a", "catter_b", pos="imports")

```


Use `library()` to load package

```{r}

# catterpoc should not be loaded at start
testthat::expect_error(catter_a("hello"), "could not find function")

library(catterpoc)

x <- catter_a("hello") 
x # print.catter_a not picked up - calling .S3method is requirement even for regular package loads

x <- catter_b("hello") 
x # Here, it is picked up correctly (because .S3method was called)


```
